[database]
host=127.0.0.1
user=root
password=
database=urlshortener
; pgsql or mysql
db=mysql


; cache for shortUrl <-> longUrl.
; Storate is Redis.
[cache]
enabled=true
hostport=localhost:6379
ttl=30