server {
	listen 82;
	root "/Library/WebServer/Documents/urlshortener";

	location / {
		fastcgi_pass 127.0.0.1:9000;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root/index.php;
	}

	location ~ \.php {
		fastcgi_pass 127.0.0.1:9000;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_script_name;
	}

	location ~ ^/[0-9a-zA-Z]+$ {
		fastcgi_pass 127.0.0.1:9000;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root/redirect.php;
		fastcgi_param PATH_INFO $fastcgi_script_name;
	}

	# static
	location ~* ^.+\.(jpg|css|js)$ {
		add_header Cache-Control no-cache;
	}
}